version: "3.8"

services:
  postgres-core:
    image: postgres:15-alpine
    container_name: postgres_core_server
    restart: always
    environment:
      # Credenciales ROOT (Necesarias para que Postgres arranque)
      POSTGRES_USER: ${POSTGRES_ROOT_USER}
      POSTGRES_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata

    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_DB_PORT}:5432"
    networks:
      - infra_network
  mongo-core:
    image: mongo:6.0
    container_name: mongo_core_server
    restart: always
    environment:
      # Usuario root para administrar Mongo
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - ./mongo-data:/data/db
    ports:
      - "${MONGO_DB_PORT}:27017"
    networks:
      - infra_network
networks:
  infra_network:
    name: infra_network
    driver: bridge
